# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmetrics.proto\x12\x07metrics\"\x11\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\"\xba\x01\n\x0bNodeMetrics\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x19\n\x11timestamp_unix_ms\x18\x04 \x01(\x03\x12\x10\n\x08\x63pu_util\x18\x05 \x01(\x01\x12\x10\n\x08mem_util\x18\x06 \x01(\x01\x12\x14\n\x0cnet_in_bytes\x18\x07 \x01(\x01\x12\x15\n\rnet_out_bytes\x18\x08 \x01(\x01\x12\x12\n\nlatency_ms\x18\t \x01(\x01\x32\x43\n\x0eMetricsService\x12\x31\n\x0bPushMetrics\x12\x14.metrics.NodeMetrics\x1a\x0c.metrics.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACK']._serialized_start=26
  _globals['_ACK']._serialized_end=43
  _globals['_NODEMETRICS']._serialized_start=46
  _globals['_NODEMETRICS']._serialized_end=232
  _globals['_METRICSSERVICE']._serialized_start=234
  _globals['_METRICSSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
